name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # pozwala GitHub wydać token OIDC
      contents: read    # pozwala czytać repo

